// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communicate.proto

package com.task3.proto;

public final class Communicate {
  private Communicate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_MapInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_MapInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_MapOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_MapOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_ReduceInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_ReduceInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_ReduceOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filesystem_ReduceOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021communicate.proto\022\nfilesystem\"S\n\010MapIn" +
      "put\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\025\n\rinputfi" +
      "lepath\030\004 \001(\t\022\026\n\016outputfilepath\030\005 \001(\t\"\036\n\t" +
      "MapOutput\022\021\n\tjobstatus\030\001 \001(\005\"V\n\013ReduceIn" +
      "put\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\025\n\rinputfi" +
      "lepath\030\004 \001(\t\022\026\n\016outputfilepath\030\005 \001(\t\"!\n\014" +
      "ReduceOutput\022\021\n\tjobstatus\030\001 \001(\0052\202\001\n\tAssi" +
      "gnJob\0226\n\003map\022\024.filesystem.MapInput\032\025.fil" +
      "esystem.MapOutput\"\000(\001\022=\n\006reduce\022\027.filesy" +
      "stem.ReduceInput\032\030.filesystem.ReduceOutp" +
      "ut\"\000B\023\n\017com.task3.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_filesystem_MapInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_filesystem_MapInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_MapInput_descriptor,
        new java.lang.String[] { "Ip", "Port", "Inputfilepath", "Outputfilepath", });
    internal_static_filesystem_MapOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_filesystem_MapOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_MapOutput_descriptor,
        new java.lang.String[] { "Jobstatus", });
    internal_static_filesystem_ReduceInput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_filesystem_ReduceInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_ReduceInput_descriptor,
        new java.lang.String[] { "Ip", "Port", "Inputfilepath", "Outputfilepath", });
    internal_static_filesystem_ReduceOutput_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_filesystem_ReduceOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filesystem_ReduceOutput_descriptor,
        new java.lang.String[] { "Jobstatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
