// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communicate.proto

package com.task3.proto;

public interface MapOutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.MapOutput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 jobstatus = 1;</code>
   * @return The jobstatus.
   */
  int getJobstatus();
}
