// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communicate.proto

package com.task3.proto;

public interface ReduceInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.ReduceInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 2;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>string inputfilepath = 4;</code>
   * @return The inputfilepath.
   */
  java.lang.String getInputfilepath();
  /**
   * <code>string inputfilepath = 4;</code>
   * @return The bytes for inputfilepath.
   */
  com.google.protobuf.ByteString
      getInputfilepathBytes();

  /**
   * <code>string outputfilepath = 5;</code>
   * @return The outputfilepath.
   */
  java.lang.String getOutputfilepath();
  /**
   * <code>string outputfilepath = 5;</code>
   * @return The bytes for outputfilepath.
   */
  com.google.protobuf.ByteString
      getOutputfilepathBytes();
}
